---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'foundation'
  # display template filenames as comments in the html output
  source_file_comments: true

Ships:
  folder_root: 'Ships'

# GalleryPage:
#   extensions: 
#     - 'Gallery_PageExtension'